# Generated by Django 4.1 on 2022-09-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
