# Generated by Django 4.1 on 2022-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleform', '0003_students_lastname_alter_students_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
