# Generated by Django 4.1 on 2022-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleform', '0004_alter_students_options_alter_students_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
