# Generated by Django 4.1 on 2022-09-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleform', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
